#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    -----------------------------------------------------
 *     transaction-get
 *     -----------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     -----------------------------------------------------
 * 
 *     This program is free software: you can redistribute
 *     it and/or modify it under the terms of the
 *     GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it
 *     will be useful, but WITHOUT ANY WARRANTY;
 *     without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *     See the GNU General Public License
 *     for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv */
const
  _argv =
    _libcrash._argv;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _dirname */
const
  _dirname =
    _libcrash._dirname;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _file_write */
const
  _file_write =
    _libcrash._file_write;
/* global
     _get */
const
  _get =
    _libcrash._get;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _globals */
const
  _globals =
    _libcrash._globals;
/* global
     _json_display */
const
  _json_display =
    _libcrash._json_display;
/* global
     _path_join */
const
  _path_join =
    _libcrash._path_join;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _printf */
const
  _printf =
    _libcrash._printf;
/* global
     _require */
const
  _require =
    _libcrash._require;
/* global
     _set */
const
  _set =
    _libcrash._set;
const
  _evm_wallet_module =
    await _require(
      "evm-wallet");
/* global
     _wallet_get */
const
  _wallet_get =
    _evm_wallet_module._wallet_get;
/* global
     _provider_get */
const
  _provider_get =
    _evm_wallet_module._provider_get;

function
  _global_variables() {
  _set(
    "app",
    "name",
    "transaction-get");
  _set(
    "retries",
    "max",
    "");
  _set(
    "wallet",
    "seed",
    "");
  _set(
    "wallet",
    "password_path",
    "");
  _set(
    "transaction",
    "address",
    "");
  _set(
    "chain",
    "id",
    "");
  _set(
    "chain",
    "name",
    "");
  _set(
    "target",
    "network",
    "");
  _set(
    "api",
    "key_path",
    "");
  _set(
    "output",
    "path",
    "");
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "";
}

function
  _msg_error_no_input_data() {
  const
    _text = [
      "You need to provide either",
      "the bytecode or the data"
    ];
  const
    _msg =
      _text.join(
        " ");
  _msg_error(
    _msg,
    1);
}

function
  _msg_info_wallet_selected(
    _wallet) {
  const
    _msg =
      `Wallet is '${_wallet}'.`;
  _msg_info(
    _msg);
}

async function
  _transaction_get(
    _retries_max,
    _wallet_seed,
    _wallet_password_path,
    _chain_id,
    _chain_name,
    _target_network,
    _api_key_path,
    _output_path,
    _transaction_address) {
  let
    _api_key,
    _get_transaction_opts,
    _network,
    _network_provider,
    _provider_get_opts,
    _tx,
    _wallet,
    _wallet_get_opts,
    _wallet_path_list,
    _wallet_path;
  _provider_get_opts = [
    _target_network
  ];
  if ( _output_path == undefined ) {
    _output_path =
      "";
  }
  if ( _api_key_path != "" ) {
    _api_key =
      _file_read(
        _api_key_path);
  }
  else if ( _api_key_path == undefined ) {
    _api_key =
      "";
  }
  _provider_get_opts.push(
    _api_key);
  if ( _chain_id == undefined ) {
    _chain_id =
      "";
  }
  _provider_get_opts.push(
    _chain_id);
  if ( _chain_name == undefined ) {
    _chain_name =
      "";
  }
  _provider_get_opts.push(
    _chain_name);
  _network_provider =
    await _provider_get.apply(
      null,
      _provider_get_opts);
  if ( _wallet_seed != "" &&
       _wallet_seed != undefined ) {
    _wallet_path_list = [
      _dirname(
        _wallet_seed),
      "wallet.dat"
    ];
    _wallet_path =
      _path_join(
        _wallet_path_list);
    _wallet_get_opts = [
      _wallet_path,
      _wallet_password_path,
      _wallet_seed,
      _network_provider
    ];
    _wallet =
      _wallet_get.apply(
        null,
        _wallet_get_opts);
    _msg_info_wallet_selected(
      _wallet);
    _network_provider =
      _wallet;
  }
  try {
    _tx =
      await _network_provider.getTransaction(
        _transaction_address);
    if ( _output_path != "" ) {
      _json =
        _json_display(
	  _tx);
      _file_write(
        _output_path,
        _json);
    }
  } catch (_error) {
    _msg_error(
      _error,
      0);
    throw _error;
  }
  return _tx;
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
      `         Maximum retries: ${retries_max}`,
      `             Wallet seed: ${wallet_seed}`,
      `             Wallet seed: ${wallet_seed}`,
      `                Chain ID: ${chain_id}`,
      `              Chain Name: ${chain_name}`,
      `          Target network: ${target_network}`,
      `                 API Key: ${api_key_path}`,
      `             Output path: ${output_path}`,
      `             Output path: ${output_path}`,
      `     Transaction address: ${transaction_address}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _app_name =
      _get(
        "app",
        "name");
  const
    _text = [
      "",
      "Retrieve EVM networks transactions",
      "",
      "Usage:",
      `  ${_app_name}`,
      "    <quiet>",
      "    <retries-max>",
      "    <wallet-seed>",
      "    <wallet-password-path>",
      "    <chain-id>",
      "    <chain-name>",
      "    <target-network>",
      "    <api-key-path>",
      "    <output-path>",
      "    <transaction-address>",
      "",
      "Args:",
      "  <quiet>                          Can be 'y' or 'n'",
      "                                   Default: y",
      "  <retries-max>                    Maximum number of retries before",
      "                                   failing.",
      "  <wallet-seed>                    Path of the seed phrase.",
      "  <wallet-password-path>           Wallet password path.",
      "  <chain-id>                       Chain ID for the network.",
      "  <chain-name>                     Name for the network.",
      "  <target-network>                 Network on which the transaction",
      "                                   resides.",
      "  <api-key-path>                   Path of the API key for the",
      "                                   network provider service.",
      "  <output-path>                    File on which to optionally save",
      "                                   the output.",
      "  <transaction-address>            Transaction one wants to retrieve.",
      "",
      "  Options:",
      "    -h                             This help.",
      ""
    ];
  for ( _line of _text ) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}

function _cmdline_parse() {
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "y";
  _argv.forEach(
    function (
      _value,
      _index) {
      if ( _index == 2 ) {
        _global[
          "quiet"] =
          _value;
      }
      if ( _index == 3 ) {
        _set(
          "retries",
          "max",
          _value);
      }
      if ( _index == 4 ) {
        _set(
          "wallet",
          "seed",
          _value);
      }
      if ( _index == 5 ) {
        _set(
          "wallet",
          "password_path",
          _value);
      }
      if ( _index == 6 ) {
        _set(
          "chain",
          "id",
          _value);
      }
      if ( _index == 7 ) {
        _set(
          "chain",
          "name",
          _value);
      }
      if ( _index == 8 ) {
        _set(
          "target",
          "network",
          _value);
      }
      if ( _index == 9 ) {
        _set(
          "api",
          "key_path",
          _value);
      }
      if ( _index == 10 ) {
        _set(
          "output",
          "path",
          _value);
      }
      if ( _index == 11 ) {
        _set(
          "transaction",
          "address",
          _value);
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _global[
          "quiet"] =
          "n";
        _usage(
	  0);
      }
    }
  );
  const
    _transaction_address =
      _get(
        "transaction",
        "address");
  if ( _transaction_address == "" ) {
    _global[
      "quiet"] =
      "n";
    _usage(
      1);
  }
}

function
  _overrides_set() {
  _override_set(
    "retries",
    "max",
    100);
  if ( chain_id == "" ) {
    _msg_info(
      "TODO: use evm_chains_info_module");
  }
  if ( chain_name == "" ) {
    _msg_info(
      "TODO: use evm_chains_info_module");
  }
}

async function
  _transaction_get_cmdline(
    _app_opts) {
  let
    _json,
    _tx;
  try {
    _tx = 
      await _transaction_get.apply(
        null,
        _app_opts);
    if ( _tx != undefined ) {
      _json =
        _json_display(
          _tx);
      _printf(
        _json);
    }
    else {
      const
        _msg =
          "Function 'transaction-get' returned undefined value.";
      const
        _exception = {
          "msg":
            _msg
        };
      throw _exception;
    }
  } catch (
      _error) {
    _msg_error(
      _error,
      1);
  }
}

if ( await _cmdline_check(
       "transaction-get") ||
     await _cmdline_check(
       "transaction-info") ) {
  _globals;
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    retries_max,
    wallet_seed,
    wallet_password_path,
    chain_id,
    chain_name,
    target_network,
    api_key_path,
    output_path,
    transaction_address
  ];
  _transaction_get_cmdline(
    app_opts);
}

export {
  _transaction_get
};

// module.exports = {
//   _transaction_get:
//     _transaction_get
// };
